// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Email2faAlertController from "./email_2fa_alert_controller"
application.register("email-2fa-alert", Email2faAlertController)
