# This workflow expects the release to be performed on a branch called `hotfix` that is branched
# from the latest release tag.
#
# Developers should create a working branch from this `hotfix` release branch with pull requests
# based against the `hotfix` release branch.
#
# Merging pull requests against the `hotfix` branch will trigger this workflow to create a new
# release pull request (if one doesn't already exist).
#
# When the release pull request is merged into `hotfix`, it will automatically create and tag a new
# release version.

name: Release automation for hotfixes
on:
  push:
    branches: [hotfix]
jobs:
  release-please:
    name: Create a new release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_TOKEN }}
          default-branch: hotfix
          release-type: ruby
          package-name: nla-blacklight_common
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          include-v-in-tag: false
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"perf","section":"Performance Improvements","hidden":false},
              {"type":"revert","section":"Reverts","hidden":false},
              {"type":"docs","section":"Documentation","hidden":false},
              {"type":"style","section":"Styles","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":false},
              {"type":"test","section":"Tests","hidden":false},
              {"type":"build","section":"Build System","hidden":false},
              {"type":"ci","section":"Continuous Integration","hidden":false}
            ]
          version-file: "lib/nla/blacklight_common/version.rb"
